// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGLFELeZwKxmD6s5vH8O5Xew3OV7QaoHs',
    appId: '1:920101289654:web:93f63da98ba6691c167017',
    messagingSenderId: '920101289654',
    projectId: 'recipeprojectdino',
    authDomain: 'recipeprojectdino.firebaseapp.com',
    storageBucket: 'recipeprojectdino.firebasestorage.app',
    measurementId: 'G-ZS0LJQ9RHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtKTgl4fjxpi2Db2hFk6otKPVk_nf8JEg',
    appId: '1:920101289654:android:fe0147b67cb5c0ba167017',
    messagingSenderId: '920101289654',
    projectId: 'recipeprojectdino',
    storageBucket: 'recipeprojectdino.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9ieyVAeJe3m0xMlexc8SLMT1qez2oKYw',
    appId: '1:920101289654:ios:96f7d1804ed70460167017',
    messagingSenderId: '920101289654',
    projectId: 'recipeprojectdino',
    storageBucket: 'recipeprojectdino.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9ieyVAeJe3m0xMlexc8SLMT1qez2oKYw',
    appId: '1:920101289654:ios:96f7d1804ed70460167017',
    messagingSenderId: '920101289654',
    projectId: 'recipeprojectdino',
    storageBucket: 'recipeprojectdino.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGLFELeZwKxmD6s5vH8O5Xew3OV7QaoHs',
    appId: '1:920101289654:web:df3e58056d06f7fa167017',
    messagingSenderId: '920101289654',
    projectId: 'recipeprojectdino',
    authDomain: 'recipeprojectdino.firebaseapp.com',
    storageBucket: 'recipeprojectdino.firebasestorage.app',
    measurementId: 'G-FL4QZD4ET1',
  );
}
